### ISSUE TITLE
Could ons_available_datasets also show the description

### ISSUE THREAD

**Issue by emmavestesson** [HFAnalyticsLab/monstR#8]
It would be good if the output from `ons_available_datasets` could also include the description of the data set as sometimes the names are not very informative.

**Comment by sw1nn** [comment]
👍 This should be implemented. In principle it should be staightforward

**Comment by sw1nn** [comment]
@emmavestesson It turns out that the descriptions are quite long and some of the other columns might be useful too. Should we have two fns? one for just the ids and one for 'everything' and then users can browse the dataframe using `utils::View`,so...

`ons_available_dataset_ids()` & `ons_available_datasets()`

**Comment by emmavestesson** [comment]
We can do two functions maybe, ons_available_datasets() staying the same and ons_dataset_description() could be the new function. Or we could keep it as one function but with an option to get 'everything' (eg ons_available_datasets(description=TRUE).

**Comment by sw1nn** [comment]
If there's a demand for an 'id' only function we can add it. In the mean time we agreed that the additional info was generally useful and that for now we'd remove the filtering and add an example of how to do the filtering at the cmd prompt
